In [2]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt

lst = [1,2,3,4]

arr = np.array(lst)

print(arr)

[1 2 3 4]


In [5]:
prices = [30,25,40,20,20,35,50,35]

new_prices = [price - 5 for price in prices]
#print(new_prices)
prices_arr = np.array(prices)
prices_arr -= 5
print(prices_arr)

[25 20 35 15 15 30 45 30]


In [22]:
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

test_3_fixed = test_3 + 2
total_grade = test_1+test_2+test_3
final_grade = total_grade / 3
print(total_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1],test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1,test_2,test_3])

print(student_scores)
print(student_scores[2][0])

print(student_scores[:][4])

[258 279 246 274 270]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87


IndexError: index 3 is out of bounds for axis 0 with size 3